server:
  port: 8000

#DATASOURCE CONFIGURATION
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/samotech?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: 1234
    generate-dll: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update